const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const workflows=JSON.parse(fs.readFileSync((process.env.CONTRACT_FIXTURE||require('node:path').join(__dirname,'workflows.fixture.json'))));
function run(code,json,refs={},workflow='workflow-A'){return new Function('$json','$','$workflow','$input','$execution',code)(json,n=>({isExecuted:!!refs[n],item:{json:refs[n]},first:()=>({json:refs[n]})}),{id:workflow},{all:()=>[{json}],first:()=>({json})},{id:'123'});}
for(const w of workflows.filter(w=>w.name!=='ComfyUI Error Reset')){
const code=n=>w.nodes.find(x=>x.name===n).parameters.jsCode;
test(w.name+' GET empty body preserves query',()=>assert.equal(run(code('Normalize Bypass Context'),{body:{},query:{RowID:'7',ByPass:'true'}})[0].json.currentId,7));
test(w.name+' captured row survives table overwrite and ID collision',()=>{const row=run(code('Capture Internal Context'),{id:7,prompt:'original'})[0].json;const out=run(code('Capture Acquired Lock'),{id:81,rowId:7,workflow:'workflow-A',executionId:'123'},{'Capture Internal Context':row})[0].json;assert.equal(out.id,7);assert.equal(out.prompt,'original');assert.deepEqual(out._context,{workflowId:'workflow-A',currentId:7,lockId:81,source:'schedule',executionId:'123'});assert.throws(()=>run(code('Capture Acquired Lock'),{id:7,rowId:81,workflow:'workflow-A'},{'Capture Internal Context':row}));assert.throws(()=>run(code('Capture Acquired Lock'),{id:81,rowId:7,workflow:'workflow-B'},{'Capture Internal Context':row}));});
test(w.name+' invalid and conflicting IDs stop',()=>{for(const Id of ['',0,-1,'01','1.2','1e3','9007199254740992'])assert.throws(()=>run(code('Normalize Bypass Context'),{body:{Id,ByPass:true}}));assert.throws(()=>run(code('Normalize Bypass Context'),{body:{Id:'7',RowID:'8',ByPass:true}}));assert.throws(()=>run(code('Normalize Bypass Context'),{body:{Id:'7',ByPass:false}}));});
test(w.name+' webhook exact row and schedule loop ownership',()=>{const ref={'Normalize Bypass Context':{currentId:7}};assert.equal(run(code('Capture Internal Context'),{id:7},ref)[0].json._context.source,'webhook');assert.throws(()=>run(code('Capture Internal Context'),{id:8},ref));for(const id of [7,8,9])assert.equal(run(code('Capture Internal Context'),{id})[0].json._context.currentId,id);});
}
