const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const fixture=JSON.parse(fs.readFileSync(process.env.DURATION_FIXTURE||path.join(__dirname,'dispatcher-duration.fixture.json')));
const code=process.env.MERGE_CODE ? fs.readFileSync(process.env.MERGE_CODE,'utf8') : JSON.parse(fs.readFileSync(path.join(__dirname,'workflows.fixture.json'))).find(w=>w.name==='Shorts Dispatcher').nodes.find(n=>n.name==='Merge Scenes + Build Jobs').parameters.jsCode;
function run(f=fixture){return new Function('$json','$input','$',code)(f.input[0].json,{all:()=>f.input},name=>{assert.equal(name,'Loop Over Items');return {item:{json:f.row}};});}
test('failed execution 57447 timeline strings build numeric Params and fixed ten-second video jobs',()=>{const out=run()[0];assert.equal(out.json.jobCount,9);for(const j of out.json.jobs){const p=JSON.parse(j.Params);assert.equal(typeof p.duration,'number');assert.equal(p.scene_id,j.SceneID.replace(/_IMG$/,''));if(j.type==='Image to video')assert.equal(p.duration,10);}assert.equal(JSON.parse(out.json.jobs[0].Params).duration,5);});

function single(raw,type='text_to_image',extra={}){const f=structuredClone(fixture);f.row.Scenes=JSON.stringify([{scene_id:'SCENE_01',...(raw===undefined?{}:{duration:raw}),...extra}]);f.input=[{json:{output:{scenes:[{scene_id:'SCENE_01',type,image_prompt:'image',video_prompt:'motion'}]}}}];return f;}
for(const [raw,seconds] of [[5,5],['5',5],['5s',5],['5 sec',5],['2.5 seconds',2.5],['5-15',10],['0-5',5],['30-45',15]])test('known duration '+JSON.stringify(raw),()=>assert.equal(JSON.parse(run(single(raw))[0].json.jobs[0].Params).duration,seconds));
for(const raw of ['',null,true,{},[],0,-1,'5-5','15-5','-5-15','5minutes','00:05','junk'])test('reject invalid duration '+JSON.stringify(raw),()=>assert.throws(()=>run(single(raw,'image_to_video')),e=>/Invalid duration: row 11, scene SCENE_01, field duration, raw/.test(e.message)&&e.message.includes('seconds')));
test('missing image duration is not fabricated; video uses explicit Rule 4a',()=>{assert.equal(JSON.parse(run(single(undefined))[0].json.jobs[0].Params).duration,undefined);assert.equal(JSON.parse(run(single(undefined,'image_to_video'))[0].json.jobs[1].Params).duration,10);});
test('preserve seed negative fps dimensions frame linkage raw Scenes',()=>{const f=single('30-45','flf_to_video',{seed:123,negativePrompt:'keep',fps:24,size:512,height:768});f.input[0].json.output.scenes[0].image_prompt='FIRST FRAME: start LAST FRAME: finish';const out=run(f)[0];assert.equal(out.json.jobCount,3);for(const j of out.json.jobs){const p=JSON.parse(j.Params);assert.equal(p.duration,10);assert.equal(p.seed,123);assert.equal(p.negativePrompt,'keep');assert.equal(p.fps,24);assert.equal(p.width,512);assert.equal(p.height,768);assert.equal(p.scene_id,'SCENE_01');}assert.deepEqual(out.json.jobs.map(j=>JSON.parse(j.Params).frame_role),['first','last','static']);assert.equal(JSON.parse(out.json.mergedScenesJson)[0].duration,'30-45');assert.deepEqual(out.pairedItem,{item:0});});
for(const fps of ['24',0,-1,null])test('fps remains strict '+JSON.stringify(fps),()=>assert.throws(()=>run(single(5,'image_to_video',{fps})),/Invalid fps: row 11, scene SCENE_01/));
