const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const html=fs.readFileSync('index.html','utf8');
function helpers(){const code=html.slice(html.indexOf('  function executionLink('),html.indexOf("  document.getElementById('metrics-refresh')"));return vm.runInNewContext(code+';({executionLink, metricModelLabel:typeof metricModelLabel===\"function\"?metricModelLabel:undefined, metricExecutionOwner:typeof metricExecutionOwner===\"function\"?metricExecutionOwner:undefined})',{escapeHtml:s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;'),escapeAttr:s=>String(s).replaceAll('"','&quot;'),colVal:(r,...names)=>r[Object.keys(r).find(k=>names.some(n=>n.toLowerCase()===k.toLowerCase()))]});}
test('Research execution stays Research even when job Type advances to Script; both renderers use owner context',()=>{const {executionLink}=helpers();const row={id:1,ExecutionID:'58229',Type:'Script',RequestKey:'x4AirppgK2nvJGuf:vN5vMR56WpEsdLMn:1'};const link=executionLink('58229',row);assert.ok(link.includes('http://10.0.0.157:5678/workflow/x4AirppgK2nvJGuf/executions/58229'));assert.match(link,/noopener noreferrer/);assert.match(link,/stopPropagation/);assert.match(html,/executionLink\(val, row\)/);assert.match(html,/executionLink\(row\[n\], metricExecutionOwner/);});
test('Unknown execution owners and invalid identifiers are never given guessed links',()=>{const {executionLink}=helpers();for(const row of [undefined,{id:1,Type:'Research'},{id:1,RequestKey:'https://evil.example:table:1'},{id:2,RequestKey:'x4AirppgK2nvJGuf:vN5vMR56WpEsdLMn:1'},{id:1,ExecutionID:'4',RequestKey:'x4AirppgK2nvJGuf:vN5vMR56WpEsdLMn:1'}])assert.ok(!executionLink('58229',row).includes('href='));for(const id of ['0','-1','1/2','123\" onclick=',''])assert.ok(!executionLink(id,{id:1,RequestKey:'wf:table:1'}).includes('href='));});
test('Metrics join by exact execution, not Task or current Type; ambiguous owners are unlinked',()=>{const {metricExecutionOwner}=helpers();const row={id:1,ExecutionID:'58229',RequestKey:'x4AirppgK2nvJGuf:vN5vMR56WpEsdLMn:1'};assert.equal(metricExecutionOwner('58229',[row]),row);assert.equal(metricExecutionOwner('58230',[row]),undefined);assert.equal(metricExecutionOwner('58229',[row,{...row,RequestKey:'other:vN5vMR56WpEsdLMn:1'}]),undefined);});
test('Metrics omits Model presentation and preserves read-only stored data',async()=>{
 const code=html.slice(html.indexOf('  async function refreshMetrics()'),html.indexOf('  function reviewSummary('));
 const parts={thead:{innerHTML:''},tbody:{innerHTML:''},status:{textContent:''}};
 const row={Task:'Research',Model:'unknown',ExecutionID:'58229',DurationMs:1234,ValidOutput:true,Error:'<unsafe>',JobID:1};
 const before=JSON.stringify(row);const reads=[];
 const owner={id:1,ExecutionID:'58229',RequestKey:'x4AirppgK2nvJGuf:vN5vMR56WpEsdLMn:1'};
 const h=helpers();
 const refresh=vm.runInNewContext(code+';refreshMetrics',{document:{getElementById:()=>({querySelector:s=>parts[s==='[data-metrics-status]'?'status':s]})},TABLES:{shorts:'shorts',comfy:'comfy'},readAllRows:async id=>{reads.push(id);return id==='MgzHSOR57oYxcmZq'?[row]:[owner]},escapeHtml:s=>String(s).replaceAll('<','&lt;').replaceAll('>','&gt;'),formatMetricDuration:v=>String(v),executionLink:h.executionLink,metricExecutionOwner:h.metricExecutionOwner});
 await refresh();
 assert.equal(parts.thead.innerHTML,'<tr><th>Task</th><th>ExecutionID</th><th>DurationMs</th><th>ValidOutput</th><th>Error</th><th>JobID</th></tr>');
 assert.ok(!parts.tbody.innerHTML.includes('model metadata'));assert.ok(!parts.tbody.innerHTML.includes('unknown'));assert.match(parts.tbody.innerHTML,/workflow\/x4AirppgK2nvJGuf\/executions\/58229/);assert.match(parts.tbody.innerHTML,/&lt;unsafe&gt;/);assert.match(parts.status.textContent,/Read-only/);assert.equal(JSON.stringify(row),before);assert.equal(row.Model,'unknown');assert.equal(reads.length,3);
});
