const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function code(name,input,refs){const w=JSON.parse(fs.readFileSync(process.env.REVIEW_WORKFLOW_FILE||'docs/review-workflow-contract.json'));const n=w.nodes.find(n=>n.name===name);return vm.runInNewContext('(function(){'+n.parameters.jsCode+'})()',{$input:{first:()=>({json:input}),all:()=>[{json:input}]},$json:input,$:name=>({first:()=>({json:refs[name]})}),Date})[0].json;}
const scenes=[{scene_id:'SCENE_03',type:'flf_to_video',duration:'12-20',voiceover:'Keep the room comfortable.',visual:'Curtains open, then curtains close in the same room.',dialogue:[]}];
const outputs=[{id:3,type:'Text to image',prompt:'Same room, curtains open.',Params:'{"scene_id":"SCENE_03","frame_role":"first"}',Dependencies:'{"version":1,"inputs":[]}'},{id:4,type:'Text to image',prompt:'Same room, curtains closed.',Params:'{"scene_id":"SCENE_03","frame_role":"last"}',Dependencies:'{"version":1,"inputs":[]}'},{id:6,type:'FLF to video',prompt:'Original curtains transformation.',Params:'{"scene_id":"SCENE_03","frame_role":"static","duration":10}',Dependencies:'{"version":1,"inputs":[{"role":"first","rowId":3},{"role":"last","rowId":4}]}'}];
const request={JobID:'2',assetId:6,action:'enhance_prompt',prompt:'Curtains open, then close smoothly in the same room.',ready:true,snapshot:'current-snapshot',outputs};
function context(){return code('Build Prompt Enhancement Context',{}, {'Evaluate Manual Decision':request,'Get Production':{id:2,Script:'Exact 20 second narration.',Scenes:JSON.stringify(scenes)}});}
test('enhancement context binds the selected type, exact scene narration and literal frame dependencies',()=>{const c=context(),s=JSON.parse(c.requestPrompt);assert.equal(s.asset.assetId,6);assert.equal(s.asset.type,'FLF to video');assert.equal(s.asset.Dependencies,outputs[2].Dependencies);assert.equal(s.sourceNarration,'Keep the room comfortable.');assert.deepEqual(JSON.parse(JSON.stringify(s.framePrerequisites.map(p=>[p.role,p.assetId]))),[['first',3],['last',4]]);assert.equal(c.beforePrompt,request.prompt);});
test('valid AI draft response is editable only and never claims generation or persistence',()=>{const c=context();const result=code('Validate Enhanced Prompt Draft',{text:JSON.stringify({enhancedPrompt:'A continuous shot preserves the first open-curtain frame and settles exactly on the supplied closed-curtain last frame.',assetType:'FLF to video',sourceNarration:'Keep the room comfortable.'})},{'Build Prompt Enhancement Context':c});assert.equal(result.assetId,6);assert.equal(result.beforePrompt,request.prompt);assert.equal(result.generationDispatched,false);assert.equal(result.persisted,false);});
test('AI errors, empty prompts, changed asset type or altered narration fail closed',()=>{const c=context();for(const bad of [{error:'model failed'},{text:''},{text:'{}'},{text:JSON.stringify({enhancedPrompt:' ',assetType:'FLF to video',sourceNarration:'Keep the room comfortable.'})},{text:JSON.stringify({enhancedPrompt:'different',assetType:'Text to image',sourceNarration:'Keep the room comfortable.'})},{text:JSON.stringify({enhancedPrompt:'different',assetType:'FLF to video',sourceNarration:'Invented words'})}])assert.throws(()=>code('Validate Enhanced Prompt Draft',bad,{'Build Prompt Enhancement Context':c}));});
