'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {createReviewHandler}=require('./review-backend.cjs');
test('validated existing binding is reused via HttpOnly cookie without browser-ID UI',async()=>{
 const root=fs.mkdtempSync('/home/dad/.hermes/cache/scratch/review-cookie-');fs.writeFileSync(path.join(root,'review-secret'),'test-private-secret');
 const upstream=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.url==='/rest/login'&&req.headers.cookie==='n8n-auth=test-native'&&req.headers['browser-id']==='original-browser-id')return res.end(JSON.stringify({data:{id:'owner',role:'global:owner'}}));res.writeHead(401);res.end('{}');});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));
 const handler=createReviewHandler({dataDir:root,n8nHost:'127.0.0.1',n8nPort:upstream.address().port,comfyHost:'127.0.0.1',comfyPort:8188,tokenFile:path.join(root,'unused')});
 async function call(headers,route='/review/session',body={}){let status,bodyResult,hs;await handler({method:'POST',headers:{origin:'http://127.0.0.1:3458',host:'127.0.0.1:3458',...headers}},{writeHead(s,h){status=s;hs=h},end(b){bodyResult=JSON.parse(b)}},route,Buffer.from(JSON.stringify(body)));return {status,body:bodyResult,headers:hs};}
 try{const a=await call({cookie:'n8n-auth=test-native','browser-id':'original-browser-id'});assert.equal(a.status,200);assert.match(a.headers['Set-Cookie'],/HttpOnly/);assert.match(a.headers['Set-Cookie'],/SameSite=Strict/);const cookie=a.headers['Set-Cookie'].split(';')[0];const b=await call({cookie:'n8n-auth=test-native; '+cookie});assert.equal(b.status,200);assert.equal(b.body.identity.id,'owner');const c=await call({cookie:'n8n-auth=changed; '+cookie});assert.equal(c.status,401);const migrated=await call({cookie:'n8n-auth=test-native','browser-id':'original-browser-id'},'/review/list',{JobID:'2',nonce:'obsolete'});assert.equal(migrated.status,403);assert.match(migrated.headers['Set-Cookie'],/HttpOnly/);}finally{await new Promise(r=>upstream.close(r));fs.rmSync(root,{recursive:true,force:true});}
});
test('mock native session binding survives CSRF renewal but never outlives native JWT expiry',async()=>{
 const realNow=Date.now,root=fs.mkdtempSync('/home/dad/.hermes/cache/scratch/review-renew-');fs.writeFileSync(path.join(root,'review-secret'),'test-private-secret');const exp=Math.floor(realNow()/1000)+3600,nativeCookie='n8n-auth=mock.'+Buffer.from(JSON.stringify({exp})).toString('base64url')+'.mock-signature';
 const upstream=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.headers.cookie===nativeCookie&&req.headers['browser-id']==='original-browser-id'&&Date.now()<exp*1000)return res.end(JSON.stringify({data:{id:'owner',role:'global:owner'}}));res.writeHead(401);res.end('{}');});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));
 const handler=createReviewHandler({dataDir:root,n8nHost:'127.0.0.1',n8nPort:upstream.address().port,comfyHost:'127.0.0.1',comfyPort:8188,tokenFile:path.join(root,'unused')});
 async function call(headers,route='/review/session',body={}){let status,bodyResult,hs;await handler({method:'POST',headers:{origin:'http://127.0.0.1:3458',host:'127.0.0.1:3458',...headers}},{writeHead(s,h){status=s;hs=h},end(b){bodyResult=JSON.parse(b)}},route,Buffer.from(JSON.stringify(body)));return {status,body:bodyResult,headers:hs};}
 try{const a=await call({cookie:nativeCookie,'browser-id':'original-browser-id'});assert.equal(a.status,200);assert.ok(a.body.expiresAt<=realNow()+600000);const cookie=a.headers['Set-Cookie'].split(';')[0];Date.now=()=>realNow()+11*60*1000;const b=await call({cookie:nativeCookie+'; '+cookie});assert.equal(b.status,200);assert.notEqual(b.body.nonce,a.body.nonce);Date.now=()=>realNow()+61*60*1000;assert.equal((await call({cookie:nativeCookie+'; '+cookie})).status,401);}finally{Date.now=realNow;await new Promise(r=>upstream.close(r));fs.rmSync(root,{recursive:true,force:true});}
});
