const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {createReviewHandler}=require('./review-backend.cjs');
test('mock scoped enhancement is authenticated, consumes its ticket, returns only a draft and renews after read-only verification',async()=>{
 const root=fs.mkdtempSync('/home/dad/.hermes/cache/scratch/enhance-route-');fs.writeFileSync(path.join(root,'review-secret'),'fixture-private');fs.writeFileSync(path.join(root,'PASSWORD'),'fixture-media');let calls=[],url,snapshot='',failAI=false;
 const upstream=http.createServer(async(req,res)=>{let text='';for await(const c of req)text+=c;res.setHeader('Content-Type','application/json');if(req.url==='/rest/login'){if(req.headers.cookie!=='n8n-auth=fixture'||req.headers['browser-id']!=='original-browser-id'){res.writeHead(401);return res.end('{}');}return res.end(JSON.stringify({data:{id:'verified-owner',role:'global:owner'}}));}if(req.url.startsWith('/view?')){res.setHeader('Content-Type','application/octet-stream');return res.end('actual mock bytes');}const b=JSON.parse(text);calls.push(b);const outputs=[{id:1,URL:url}];if(b.action==='inspect')return res.end(JSON.stringify({JobID:'2',ready:true,outputs}));if(b.action==='list'||b.action==='verify'){const s=JSON.stringify(b.fingerprints);if(b.action==='list')snapshot=s;return res.end(JSON.stringify({JobID:'2',ready:true,outputs,snapshot:s,State:'pending'}));}if(b.action==='enhance_prompt'){if(failAI)return res.end(JSON.stringify({error:'model_failed',message:'Native AI failed'}));return res.end(JSON.stringify({JobID:'2',assetId:b.assetId,beforePrompt:b.prompt,enhancedPrompt:'Improved '+b.prompt,snapshot,generationDispatched:false,persisted:false}));}throw Error('Unexpected write/dispatch action '+b.action);});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));const port=upstream.address().port;url='http://127.0.0.1:'+port+'/view?filename=fixture.png';
 const handler=createReviewHandler({dataDir:root,n8nHost:'127.0.0.1',n8nPort:port,comfyHost:'127.0.0.1',comfyPort:port,tokenFile:path.join(root,'PASSWORD')});
 async function call(route,body,headers={}){let status,data;await handler({method:'POST',headers:{host:'127.0.0.1:3458',origin:'http://127.0.0.1:3458',cookie:'n8n-auth=fixture','browser-id':'original-browser-id',...headers}},{writeHead:s=>status=s,end:b=>data=JSON.parse(b)},route,Buffer.from(JSON.stringify(body)));return {status,data};}
 try{const session=await call('/review/session',{}),nonce=session.data.nonce;const list=await call('/review/list',{JobID:'2',nonce});const body={JobID:'2',assetId:1,prompt:'a selected draft',nonce,decisionNonce:list.data.decisionNonce,approvedBy:'client-forgery'};
 const enhanced=await call('/review/enhance',body);assert.equal(enhanced.status,200);assert.equal(enhanced.data.enhancedPrompt,'Improved a selected draft');assert.equal(enhanced.data.persisted,false);assert.equal(enhanced.data.generationDispatched,false);assert.notEqual(enhanced.data.decisionNonce,list.data.decisionNonce);assert.equal(calls.find(c=>c.action==='enhance_prompt').approvedBy,'verified-owner');assert.ok(calls.some(c=>c.action==='verify'));assert.equal((await call('/review/enhance',body)).status,403);
 assert.equal((await call('/review/enhance',{...body,decisionNonce:enhanced.data.decisionNonce,prompt:' '})).status,400);failAI=true;assert.equal((await call('/review/enhance',{...body,decisionNonce:enhanced.data.decisionNonce})).status,409);
 assert.equal((await call('/review/enhance',body,{cookie:''})).status,401);assert.equal((await call('/review/enhance',body,{origin:'http://evil.invalid'})).status,403);assert.ok(calls.every(c=>!['approve_asset','reject_asset','regenerate'].includes(c.action)));
 }finally{await new Promise(r=>upstream.close(r));fs.rmSync(root,{recursive:true,force:true});}
});
