'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const root='/home/dad/Config/production-readiness/per-asset-review';
function run(name,input,refs){const w=JSON.parse(fs.readFileSync(process.env.REVIEW_WORKFLOW_FILE||'docs/review-workflow-contract.json'));return vm.runInNewContext('(function(){'+w.nodes.find(n=>n.name===name).parameters.jsCode+'})()',{$input:{all:()=>input.map(json=>({json})),first:()=>({json:input[0]})},$json:input[0],$:name=>({first:()=>({json:refs[name]}),all:()=>((refs[name]||[]).map(json=>({json})))}),Date}).map(x=>JSON.parse(JSON.stringify(x.json)));}
const URL='http://10.0.0.157:8188/view?filename=a.png';
const image={id:1,JobID:'2',type:'Text to image',Completed:true,Working:false,URL,prompt:'frame',Params:'{"scene_id":"s","frame_role":"source"}',Dependencies:'{"version":1,"inputs":[]}',LastError:''};
const video={...image,id:2,type:'Image to video',URL:URL.replace('png','mp4'),Params:'{"scene_id":"s","frame_role":"static"}',Dependencies:'{"version":1,"inputs":[{"role":"source","rowId":1}]}'};
const parent={id:2,Type:'Review',Status:'Queued',Working:false,Script:'exact',Scenes:'[{"scene_id":"s","type":"image_to_video"}]'};
const req={JobID:'2',action:'list',approvedBy:'owner',fingerprints:[image,video].map(x=>({id:x.id,URL:x.URL,sha256:'a'.repeat(64),bytes:10}))};
function capture(rows=[image,video],request=req){return run('Capture Output Snapshot',rows,{'Review Request':request,'Get Production':parent})[0];}
function decide(current,old=[]){return run('Evaluate Manual Decision',old,{'Capture Output Snapshot':current})[0];}
test('one asset approval does not approve job or permit assembly',()=>{const c=capture(),listed=decide(c);const d=decide({...c,action:'approve_asset',assetId:1,expectedSnapshot:c.snapshot},[{...listed,Outputs:listed.Outputs}]);assert.equal(d.State,'pending');assert.equal(JSON.parse(d.Outputs)[0].review.state,'approved');assert.equal(JSON.parse(d.Outputs)[1].review.state,'pending');assert.equal(d.FinalGenerationAllowed,false);});
test('last required approval persists all-approved without inventing absent assembly',()=>{const c=capture(),l=decide(c);const a=decide({...c,action:'approve_asset',assetId:1,expectedSnapshot:c.snapshot},[l]);const b=decide({...c,action:'approve_asset',assetId:2,expectedSnapshot:c.snapshot},[a]);assert.equal(b.State,'approved');assert.equal(b.approvedCount,2);assert.equal(b.assemblyAvailable,false);assert.match(b.nextStep,/not configured/);});
test('reject persists only selected asset and blocks aggregate approval',()=>{const c=capture(),l=decide(c);const a=decide({...c,action:'reject_asset',assetId:2,reason:'bad',expectedSnapshot:c.snapshot},[l]);assert.equal(a.State,'rejected');assert.equal(a.outputs[1].review.reason,'bad');assert.equal(a.outputs[0].review.state,'pending');});
test('changed file hash invalidates only changed asset approval',()=>{const c=capture(),l=decide(c),a=decide({...c,action:'approve_asset',assetId:1,expectedSnapshot:c.snapshot},[l]);const changed=capture([image,video],{...req,fingerprints:req.fingerprints.map((f,i)=>({...f,sha256:(i===0?'b':'a').repeat(64)}))});assert.equal(decide(changed,[a]).outputs[0].review.state,'pending');assert.throws(()=>decide({...changed,action:'approve_asset',assetId:1,expectedSnapshot:c.snapshot},[a]));});
test('whole-job legacy approval cannot bypass individual approvals',()=>{const c=capture(),l=decide(c);assert.throws(()=>decide({...c,action:'approve',expectedSnapshot:c.snapshot},[l]),/Whole-job/);});
test('readiness rejects LastError, wrong dependencies and unsupported assets',()=>{assert.equal(capture([{...image,LastError:'failed'},video]).ready,false);assert.equal(capture([image,{...video,Dependencies:'{"version":1,"inputs":[{"role":"source","rowId":99}]}'}]).ready,false);assert.equal(capture([image,{...video,type:'unsupported'}]).ready,false);});
test('source snapshot includes exact dependency bindings and active production flags',()=>{const c=capture();assert.equal(JSON.parse(c.snapshot).outputs[1].Dependencies,video.Dependencies);assert.equal(JSON.parse(c.snapshot).production.Working,false);});
test('regenerate clears selected and dependent approvals and preserves prior files in history',()=>{const c=capture(),l=decide(c),a=decide({...c,action:'approve_asset',assetId:1,expectedSnapshot:c.snapshot},[l]),b=decide({...c,action:'approve_asset',assetId:2,expectedSnapshot:c.snapshot},[a]);const r=decide({...c,action:'regenerate',assetId:1,prompt:'new exact frame',expectedSnapshot:c.snapshot},[b]);assert.equal(r.State,'pending');assert.ok(r.outputs.every(o=>o.review.state==='pending'));assert.equal(r.outputs[0].history[0].URL,image.URL);assert.equal(r.outputs[0].history[0].submittedPrompt,'new exact frame');});
test('regeneration plan targets selected row plus exact dependent video only',()=>{const c=capture(),l=decide(c),r=decide({...c,action:'regenerate',assetId:1,prompt:'new exact frame',expectedSnapshot:c.snapshot},[l]);const plan=run('Prepare Asset Regeneration',[],{'Evaluate Manual Decision':r,'Get Generation Jobs':[image,video],'Get Active Owners':[]});assert.equal(plan.length,2);assert.equal(plan[0].id,1);assert.equal(plan[0].prompt,'new exact frame');assert.match(plan[0].LastError,/Review regeneration pending explicit dispatch/);assert.equal(plan[1].id,2);assert.match(plan[1].LastError,/explicit regeneration/);assert.equal(plan[1].prompt,video.prompt);assert.ok(plan.every(p=>p.Completed===false));});
test('initial readiness requires complete source scene asset bundles',()=>{const missing=capture([image],{...req,fingerprints:[req.fingerprints[0]]});assert.equal(missing.ready,false);});
test('missing previously enrolled required asset fails closed instead of silently shrinking job',()=>{const c=capture(),l=decide(c);const changed={...c,outputs:[c.outputs[0]],snapshot:JSON.stringify({...JSON.parse(c.snapshot),outputs:[c.outputs[0]]})};assert.throws(()=>decide(changed,[l]),/required asset/);});
test('unrelated workflow owners with the same numeric row ID do not block this queue',()=>{const c=capture(),l=decide(c);const result=run('Evaluate Manual Decision',[l],{'Capture Output Snapshot':{...c,action:'approve_asset',assetId:1,expectedSnapshot:c.snapshot},'Get Active Owners':[{rowId:1,workflow:'other-production-stage'}]})[0];assert.equal(result.approvedCount,1);const r=decide({...c,action:'regenerate',assetId:1,prompt:'changed',expectedSnapshot:c.snapshot},[l]);assert.equal(run('Prepare Asset Regeneration',[],{'Evaluate Manual Decision':r,'Get Generation Jobs':[image,video],'Get Active Owners':[{rowId:1,workflow:'other-production-stage'}]}).length,2);});
test('regeneration refuses live owners and blank prompts',()=>{const c=capture(),l=decide(c);assert.throws(()=>decide({...c,action:'regenerate',assetId:1,prompt:' ',expectedSnapshot:c.snapshot},[l]));const r=decide({...c,action:'regenerate',assetId:1,prompt:'frame',expectedSnapshot:c.snapshot},[l]);assert.throws(()=>run('Prepare Asset Regeneration',[],{'Evaluate Manual Decision':r,'Get Generation Jobs':[image,video],'Get Active Owners':[{rowId:1}]}),/owner/);});
