const {test}=require('node:test');
test('column parser returns synchronous JSON arrays for create-table payloads',()=>{const html=fs.readFileSync('index.html','utf8');const c={};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  async function parseColumns(')>=0?html.indexOf('  async function parseColumns('):html.indexOf('  function parseColumns('),html.indexOf('  function showNewStatus(')),c);assert.equal(JSON.stringify(c.parseColumns('[{"name":"label"}]')),'[{"name":"label"}]');assert.equal(c.parseColumns(''),null);});
test('canonical job types retain unknown identifiers',()=>{const html=fs.readFileSync('index.html','utf8');const c={};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  function canonicalType('),html.indexOf('  // ─── Webhook')),c);assert.equal(c.canonicalType('text_to_image'),'Text to image');assert.equal(c.canonicalType('image_to_video'),'Image to video');assert.equal(c.canonicalType('flf_to_video'),'FLF to video');assert.equal(c.canonicalType('custom'),'custom');});
test('rejects structured validation errors even with HTTP200',async()=>{const c=helpers();c.fetch=async()=>({ok:true,status:200,text:async()=>JSON.stringify([{error:'invalid_request',message:'limit must be <=250',statusCode:400}])});await assert.rejects(c.api.callWebhook('/yt-get',{}),/invalid_request.*limit/);});

const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
test('template previews never invent an API column in queue rows',()=>{const html=fs.readFileSync('index.html','utf8');const c={state:{templates:[{type:'Text to image',API:'{}'}],rows:[{id:1,type:'text_to_image',Params:'{"seed":0}'}]},renderPanels(){},log(){},canonicalType:()=> 'Text to image'};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  function enrichRowsWithTemplateAPI('),html.indexOf('  // ─── Case-insensitive')),c);c.enrichRowsWithTemplateAPI();assert.equal(Object.hasOwn(c.state.rows[0],'API'),false);});
test('saving a canonical type does not send nonexistent API columns',async()=>{const html=fs.readFileSync('index.html','utf8');const calls=[];const inp={value:'Text to image',closest:()=>({querySelector:()=>({textContent:'type'})})};const c={TABLES:{shorts:'jobs',comfy:'correct'},state:{modalRow:{id:4,type:'text_to_image'},modalTableId:'correct',currentTableId:'other',modalMode:'edit',templates:[{type:'Text to image',API:'{}'}]},$:()=>({querySelectorAll:()=>[inp]}),isTrackingCol:k=>['executionid','attemptcount','lasterror','requestkey'].includes(k.toLowerCase()),colKey:k=>k.toLowerCase(),isCol:(k,...cs)=>cs.includes(k),canonicalType:t=>t,setStatus(){},log(){},callWebhook:async(p,b)=>calls.push(b),closeModal(){},setTimeout(){}};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  async function sendPatch('),html.indexOf('  // ─── Config load')),c);await c.sendPatch();assert.equal(calls[0].id,'correct');assert.equal(Object.hasOwn(calls[0].row,'API'),false);assert.equal(calls[0].row.type,'Text to image');});
test('ComfyUI output previews retain direct credential-free URLs',()=>{const html=fs.readFileSync('index.html','utf8');const c={URL,location:{origin:'http://localhost:3458'}};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  function browserOutputURL('),html.indexOf('  function renderURL(')),c);assert.equal(c.browserOutputURL('http://10.0.0.157:8188/view?filename=clip.mp4&subfolder=videos'),'http://10.0.0.157:8188/view?filename=clip.mp4&subfolder=videos');assert.equal(c.browserOutputURL('http://evil:8188/view?filename=x'),'http://evil:8188/view?filename=x');});
test('entire shipped browser script compiles and Config controls exist',()=>{const html=fs.readFileSync('index.html','utf8');assert.doesNotThrow(()=>new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1]));for(const id of ['panel-config','cfg-table-home','cfg-table-jobs','cfg-table-templates','cfg-table-link','cfg-webhook-base','cfg-n8n-host','cfg-n8n-port','cfg-api-base','cfg-api-port','cfg-proxy-base','cfg-refresh-interval','cfg-max-debug-lines','cfg-debug-default','cfg-auto-refresh-default','btn-save-config','btn-reset-config','cfg-status'])assert.ok(html.includes('id="'+id+'"'),id+' missing');});
test('review readiness is complete-only and stale snapshots lose approved display',()=>{const html=fs.readFileSync('index.html','utf8');const c={URL};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  function reviewSummary('),html.indexOf('  async function refreshReview(')),c);const jobs=[{id:1,type:'Text to image',URL:'http://test/out',Completed:true,Working:false,Params:'{}',prompt:'p'}];const a=c.reviewSummary({Status:'Qued'},jobs,[]);assert.equal(a.ready,true);assert.equal(a.state,'not listed');const approved=[{Snapshot:a.snapshot,State:'approved'}];assert.equal(c.reviewSummary({Status:'Qued'},jobs,approved).state,'approved');assert.equal(c.reviewSummary({Status:'Qued'},[{...jobs[0],URL:'http://test/new'}],approved).state,'stale — list again');assert.equal(c.reviewSummary({Status:'Qued'},[{...jobs[0],Completed:false}],approved).ready,false);assert.equal(c.reviewSummary({Status:'Working'},jobs,approved).ready,false);assert.equal(c.reviewSummary({Status:'Qued'},[],approved).ready,false);});
test('Params validation preserves zero seed and empty explicit negative prompt',()=>{const html=fs.readFileSync('index.html','utf8');const c={};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  function validateParams('),html.indexOf('  // ─── Webhook')),c);assert.equal(c.validateParams('{"seed":0,"negativePrompt":"","scene_id":"s"}'),'{"seed":0,"negativePrompt":"","scene_id":"s"}');assert.throws(()=>c.validateParams('{bad'),/Params/);assert.throws(()=>c.validateParams('{"seed":-1}'),/seed/);assert.throws(()=>c.validateParams('{"negativePrompt":4}'),/negativePrompt/);assert.throws(()=>c.validateParams('[]'),/object/);});
test('push dispatches the exact existing row without pre-lock or cloning',async()=>{const html=fs.readFileSync('index.html','utf8');const requests=[];const c={TABLES:{comfy:'table',shorts:'shorts'},state:{currentTableId:'table',rowsTableId:'table',rows:[{id:12,type:'text_to_image',Params:'{"seed":0,"negativePrompt":"bad"}',Working:false}]},setStatus(){},log(){},setTimeout(){},fetch:async(p,b)=>{requests.push({p,b});return {ok:true,status:200,text:async()=>'{"accepted":true}'};},colVal:(r,k)=>r[k],canonicalType:t=>t==='text_to_image'?'Text to image':t};Object.assign(c,{window:{addEventListener(){}},document:{querySelector:()=>null},activeJobStage:"research",pushRefreshRole:()=>"home",schedulePushRefresh(){}});vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  function canPushRow('),html.indexOf('  // ─── Modal')),c);await c.doPush('12','text_to_image');assert.equal(requests[0].p,'/dispatch/runner');assert.equal(JSON.parse(requests[0].b.body).rowId,'12');assert.equal(c.state.rows[0].Working,false);assert.equal(c.state.rows[0].Params,'{"seed":0,"negativePrompt":"bad"}');});
test('media URL roundtrip preserves image/video metadata and refuses credential parameters',()=>{const html=fs.readFileSync('index.html','utf8');const c={URL,location:{origin:'http://10.0.0.157:3458'}};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  function browserOutputURL('),html.indexOf('  function renderURL(')),c);for(const filename of ['z-image-turbo_00151_.png','LTX-2.5_i2v_00110_.mp4','a &+.mp4']){const original=new URL('http://10.0.0.157:8188/view');original.search=new URLSearchParams({filename,subfolder:'video',type:'output'});const mapped=new URL(c.browserOutputURL(original.href));assert.equal(mapped.href,original.href);assert.equal(mapped.origin,'http://10.0.0.157:8188');assert.equal(mapped.searchParams.get('filename'),filename);assert.equal(mapped.searchParams.get('subfolder'),'video');assert.equal(mapped.searchParams.get('type'),'output');}assert.equal(c.browserOutputURL('http://10.0.0.157:8188/view?filename=a.png&token=secret'),'');});
function helpers(){const html=fs.readFileSync('index.html','utf8');const part=html.slice(html.indexOf('  async function callWebhook('),html.indexOf('  async function loadTable('));const context={fetch:null,log(){},getWebhookBase:()=>'/webhook',Pipeline:undefined};vm.createContext(context);vm.runInContext(part+';this.api={callWebhook,readAllRows,unwrapRows};',context);return context;}
test('reads all cursor pages with max250 and preserves rows',async()=>{const c=helpers();const requests=[];c.fetch=async(url,opts)=>{const b=JSON.parse(opts.body);requests.push(b);return {ok:true,status:200,text:async()=>JSON.stringify([{data:[{id:requests.length,Params:'{"seed":0,"negativePrompt":"bad"}'}],nextCursor:requests.length===1?'next':null}])};};const rows=await c.api.readAllRows('table');assert.equal(rows.length,2);assert.equal(requests[0].limit,250);assert.equal(requests[1].cursor,'next');assert.equal(JSON.parse(rows[0].Params).seed,0);});

test('image and video render originals and fallback links without proxy conversion',()=>{
 const html=fs.readFileSync('index.html','utf8');const listeners={};const c={URL,document:{addEventListener:(name,fn)=>listeners[name]=fn,createElement:()=>({})}};
 vm.createContext(c);vm.runInContext(html.slice(html.indexOf('  function browserOutputURL('),html.indexOf('  function renderAPI(')),c);
 for(const [name,tag] of [['still &+.png','img'],['clip &+.mp4','video']]){
  const original='http://10.0.0.157:8188/view?filename='+encodeURIComponent(name)+'&subfolder=video%2Fnested%20space&type=temp';
  assert.equal(c.browserOutputURL(original),original);const output=c.renderURL({},original);assert.ok(output.includes('<'+tag));assert.ok(output.includes('src="'+c.escapeAttr(original)+'"'));assert.ok(!output.includes('/media/comfy/view'));
  let link;listeners.error({target:{tagName:tag.toUpperCase(),hasAttribute:()=>true,getAttribute:()=>original,replaceWith:a=>link=a}});assert.equal(link.href,original);
 }
 assert.ok(!html.includes('/media/comfy/view'));
});
