const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const html=fs.readFileSync('index.html','utf8');
test('New exposes only Production Job Idea, not table or Comfy creation',()=>{const panel=html.split('<div class="tab-panel" id="panel-new">')[1].split('<div class="tab-panel" id="panel-setup">')[0];assert.ok(panel.includes('production-idea-form'));assert.ok(!panel.includes('btn-create-table'));assert.ok(!panel.includes('new-cols'));assert.ok(!panel.includes('New Table'));assert.ok(!panel.includes('Template API'));});
function builder(){const match=html.match(/function productionIdeaRow\(idea\) \{([\s\S]*?)\n  \}/);assert.ok(match,'production idea builder exists');return vm.runInNewContext('(function(idea){'+match[1]+'})');}
test('Production idea uses actual Research schema and native pending flags',()=>{const row=builder()('  A useful idea  ');assert.deepEqual(JSON.parse(JSON.stringify(row)),{Type:'Research',Ideas:'A useful idea',Status:'Idea',Completed:false,Working:false,AttemptCount:0,LastError:'',ExecutionID:'',RequestKey:''});assert.throws(()=>builder()('   '),/required/);});

function harness({failure,readback,source}={}) {
 const nodes=Object.fromEntries(['production-idea','production-idea-create','production-idea-status','production-idea-jobs'].map(id=>[id,{value:id==='production-idea'?'A useful idea':'',hidden:true,dataset:{}}]));
 const calls=[];let reads=0;const row={id:42,Type:'Research',Ideas:'A useful idea',Status:'Idea',Completed:false,Working:false,AttemptCount:0,LastError:'',ExecutionID:'',RequestKey:''};
 const script=html.slice(html.indexOf('  function productionIdeaRow('),html.indexOf("  $('#production-idea-form').addEventListener"));
 const context={Number,Set,Error,String,Object,Array,TABLES:{shorts:source||'production',comfy:'comfy'},state:{currentTableId:'comfy'},$:s=>nodes[s.slice(1)],renderPanels(){},readAllRows:async()=>{reads++;return reads===1?[]:readback||[row]},callWebhook:async(path,payload)=>{calls.push({path,payload});if(failure)throw failure;return [{success:true,insertedRows:1}]}};
 vm.createContext(context);vm.runInContext(script,context);return {context,nodes,calls,submit:()=>vm.runInContext('createProductionIdea({preventDefault(){}})',context)};
}
test('Create writes once to production, verifies real acknowledgement/readback and never dispatches',async()=>{const h=harness();await Promise.all([h.submit(),h.submit()]);assert.equal(h.calls.length,1);assert.deepEqual(JSON.parse(JSON.stringify(h.calls[0])),{path:'/yt-wright',payload:{operation:'write',id:'production',row:{data:[{Type:'Research',Ideas:'A useful idea',Status:'Idea',Completed:false,Working:false,AttemptCount:0,LastError:'',ExecutionID:'',RequestKey:''}]}}});assert.equal(h.nodes['production-idea'].value,'');assert.match(h.nodes['production-idea-status'].textContent,/#42/);assert.equal(h.context.state.otherTableId,'production');});
test('Unknown write failure preserves text and blocks duplicate retries',async()=>{const h=harness({failure:new Error('timeout')});await h.submit();await h.submit();assert.equal(h.calls.length,1);assert.equal(h.nodes['production-idea'].value,'A useful idea');assert.equal(h.nodes['production-idea-create'].disabled,true);});
test('Validation errors retain text and allow corrected retry',async()=>{const h=harness({failure:Object.assign(new Error('invalid_request'),{status:400})});await h.submit();assert.equal(h.nodes['production-idea-create'].disabled,false);assert.equal(h.nodes['production-idea'].value,'A useful idea');});
test('Readback mismatch and wrong table cannot claim success',async()=>{const h=harness({readback:[]});await h.submit();assert.equal(h.nodes['production-idea-create'].disabled,true);assert.equal(h.nodes['production-idea'].value,'A useful idea');const wrong=harness({source:'comfy'});await wrong.submit();assert.equal(wrong.calls.length,0);});
