const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {createReviewHandler}=require('./review-backend.cjs');
test('mock transport: streaming hashes, native identity, single-use/expiry/logout/member and fixed URL guards',async()=>{
 const root=fs.mkdtempSync('/home/dad/.hermes/cache/scratch/review-security-');fs.writeFileSync(path.join(root,'review-secret'),'test-header-only');fs.writeFileSync(path.join(root,'PASSWORD'),'test-media-only');let user={id:'native-owner',role:'global:owner'},logged=true,redirect=false,ready=true,calls=[],outputURL;let snap='';
 const native=http.createServer(async(req,res)=>{let b='';for await(const c of req)b+=c;calls.push({url:req.url,headers:req.headers,body:b?JSON.parse(b):null});if(req.url==='/rest/login'){res.setHeader('Content-Type','application/json');res.statusCode=logged?200:401;return res.end(JSON.stringify({data:user}));}if(req.url.startsWith('/view?')){if(redirect){res.writeHead(302,{Location:'http://evil.invalid/'});return res.end();}assert.equal(req.headers.authorization,'Bearer test-media-only');return res.end('actual mock fixture bytes');}assert.equal(req.headers['x-review-transport'],'test-header-only');const p=JSON.parse(b);const outputs=[{id:1,URL:outputURL}];res.setHeader('Content-Type','application/json');if(p.action==='inspect')return res.end(JSON.stringify({outputs,ready}));if(p.action==='list'){snap=JSON.stringify(p.fingerprints);return res.end(JSON.stringify({snapshot:snap,outputs,ready:true,State:'pending'}));}return res.end(JSON.stringify({State:p.action==='approve_asset'?'approved':'rejected',snapshot:snap}));});await new Promise(r=>native.listen(0,'127.0.0.1',r));const port=native.address().port;outputURL='http://127.0.0.1:'+port+'/view?filename=fixture.png';const origin='http://127.0.0.1:3458';const old=process.env.REVIEW_UI_ORIGINS;process.env.REVIEW_UI_ORIGINS=origin;const handler=createReviewHandler({dataDir:root,n8nHost:'127.0.0.1',n8nPort:port,comfyHost:'127.0.0.1',comfyPort:port,tokenFile:path.join(root,'PASSWORD')});
 async function send(route,body,headers={}){let status,data;const req={method:'POST',headers:{host:'127.0.0.1:3458',origin,Cookie:undefined,cookie:'n8n-auth=test-cookie','browser-id':'test-browser-id',...headers}};await handler(req,{writeHead:s=>status=s,end:b=>data=JSON.parse(b)},route,Buffer.from(JSON.stringify(body)));return {status,data};}
 const realNow=Date.now;
 try{
 const s=await send('/review/session',{});assert.equal(s.status,200);const nonce=s.data.nonce;
 ready=false;const priorDownloadCount=calls.filter(c=>c.url.startsWith('/view?')).length;assert.equal((await send('/review/list',{JobID:'1',nonce})).status,409);assert.equal(calls.filter(c=>c.url.startsWith('/view?')).length,priorDownloadCount);ready=true;
 const listed=await send('/review/list',{JobID:'1',nonce,approvedBy:'evil-client-role'});assert.equal(listed.status,200);const lastList=calls.findLast(x=>x.body?.action==='list');assert.equal(lastList.body.approvedBy,'native-owner');assert.equal(lastList.body.fingerprints[0].sha256,crypto.createHash('sha256').update('actual mock fixture bytes').digest('hex'));
 const d={JobID:'1',nonce,decisionNonce:listed.data.decisionNonce,action:'approve_asset',assetId:1,reason:''};assert.equal((await send('/review/decision',d)).status,200);assert.equal((await send('/review/decision',d)).status,403);
 const l2=await send('/review/list',{JobID:'1',nonce});logged=false;assert.equal((await send('/review/decision',{...d,decisionNonce:l2.data.decisionNonce})).status,401);logged=true;user.role='global:member';assert.equal((await send('/review/session',{})).status,403);user.role='global:owner';
 Date.now=()=>realNow()+11*60*1000;assert.equal((await send('/review/list',{JobID:'1',nonce})).status,403);Date.now=realNow;
 const s2=await send('/review/session',{});const n2=s2.data.nonce;redirect=true;assert.equal((await send('/review/list',{JobID:'1',nonce:n2})).status,409);redirect=false;outputURL='http://evil.invalid/view?filename=x';assert.equal((await send('/review/list',{JobID:'1',nonce:n2})).status,400);
 assert.ok(calls.filter(x=>x.url==='/rest/login').every(x=>!x.headers['x-n8n-api-key']));assert.ok(calls.filter(x=>x.url!=='/rest/login').every(x=>!x.headers.cookie));
 }finally{Date.now=realNow;if(old===undefined)delete process.env.REVIEW_UI_ORIGINS;else process.env.REVIEW_UI_ORIGINS=old;await new Promise(r=>native.close(r));fs.rmSync(root,{recursive:true,force:true});}
});
