'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {createReviewHandler}=require('./review-backend.cjs');
test('trusted LAN listing without cookies verifies files and issues a job-bound nonce',async()=>{
 const root=fs.mkdtempSync('/home/dad/.hermes/cache/scratch/review-lan-');fs.writeFileSync(path.join(root,'review-secret'),'private-test-secret');fs.writeFileSync(path.join(root,'token'),'media-secret');let calls=[];
 const media=http.createServer((q,s)=>s.end('actual fixture bytes'));await new Promise(r=>media.listen(0,'127.0.0.1',r));
 const upstream=http.createServer((q,s)=>{let b='';q.on('data',c=>b+=c);q.on('end',()=>{calls.push({url:q.url,body:JSON.parse(b),header:q.headers['x-review-transport']});s.setHeader('Content-Type','application/json');s.end(JSON.stringify({JobID:'2',ready:true,snapshot:'snapshot',outputs:[{id:6,URL:'http://127.0.0.1:'+media.address().port+'/view?filename=fixture.png'}]}));});});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));
 const handler=createReviewHandler({dataDir:root,n8nHost:'127.0.0.1',n8nPort:upstream.address().port,comfyHost:'127.0.0.1',comfyPort:media.address().port,tokenFile:path.join(root,'token')});
 async function call(body,origin='http://127.0.0.1:3458',route='/review/list',method='POST'){let status,result;await handler({method,headers:{origin,host:'127.0.0.1:3458'}},{writeHead(s){status=s},end(b){result=JSON.parse(b)}},route,Buffer.from(JSON.stringify(body)));return {status,result};}
 try{const a=await call({JobID:'2'});assert.equal(a.status,200);assert.ok(a.result.decisionNonce);assert.equal(calls.length,2);assert.ok(calls.every(c=>c.body.trustSource==='trusted-lan-ui'&&c.body.approvedBy==='trusted-LAN Web UI'&&c.header==='private-test-secret'));assert.equal((await call({JobID:'2'},'http://evil.test')).status,403);assert.equal((await call({JobID:'02'})).status,400);assert.equal((await call({JobID:'2'},undefined,'/review/list','GET')).status,405);const wrong=await call({JobID:'3',assetId:6,action:'approve_asset',reason:'',decisionNonce:a.result.decisionNonce},undefined,'/review/decision');assert.equal(wrong.status,409);assert.equal(calls.length,2);}finally{await Promise.all([new Promise(r=>upstream.close(r)),new Promise(r=>media.close(r))]);fs.rmSync(root,{recursive:true,force:true});}
});
