const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const file=process.env.REVIEW_WORKFLOW_FILE||'docs/review-workflow-contract.json';
function code(name,input,refs){const w=JSON.parse(fs.readFileSync(file));const n=w.nodes.find(x=>x.name===name);return vm.runInNewContext('(function(){'+n.parameters.jsCode+'})()',{$input:{first:()=>({json:input[0]}),all:()=>input.map(json=>({json}))},$json:input[0],$:name=>({first:()=>({json:refs[name]}),all:()=>((refs[name]||[]).map(json=>({json})))}),Date});}
const job={id:1,JobID:'1',type:'Text to image',URL:'http://10.0.0.157:8188/view?filename=fixture.png',Completed:true,Working:false,Params:'{"scene_id":"s","frame_role":"static"}',Dependencies:'{"version":1,"inputs":[]}',prompt:'fixture'};
const parent={id:1,Type:'Review',Working:false,Status:'Queued',Script:'script',Scenes:'[{"scene_id":"s","type":"text_to_image"}]'};
const request={JobID:'1',action:'list',approvedBy:'verified-owner',fingerprints:[{id:1,URL:job.URL,sha256:'a'.repeat(64),bytes:123}]};
test('native snapshot binds source metadata and server file hashes',()=>{const r=code('Capture Output Snapshot',[job],{'Review Request':request,'Get Production':parent})[0].json;assert.equal(r.ready,true);const s=JSON.parse(r.snapshot);assert.equal(s.production.Script,'script');assert.equal(s.outputs[0].sha256,'a'.repeat(64));assert.equal(s.outputs[0].bytes,123);});
test('native rejects hash mapping that differs from fresh output',()=>{assert.throws(()=>code('Capture Output Snapshot',[job],{'Review Request':{...request,fingerprints:[{...request.fingerprints[0],URL:job.URL+'x'}]},'Get Production':parent}));});
test('native decision rejects stale source and incomplete approval',()=>{assert.throws(()=>code('Evaluate Manual Decision',[{JobID:'1',Snapshot:'old'}],{'Capture Output Snapshot':{...request,snapshot:'fresh',expectedSnapshot:'old',ready:true,outputs:[],action:'approve_asset',assetId:1}}));assert.throws(()=>code('Evaluate Manual Decision',[{JobID:'1',Snapshot:'same'}],{'Capture Output Snapshot':{...request,snapshot:'same',expectedSnapshot:'same',ready:false,outputs:[],action:'approve_asset',assetId:1}}));});
