'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),os=require('node:os');
const {buildRequiredTables,createSetupHandler}=require('./setup-bootstrap.cjs');
const tables=JSON.parse(fs.readFileSync('full-stack/tables.json')),templates=JSON.parse(fs.readFileSync('full-stack/templates.json'));
function fixture(){const stored=[],rows=new Map(),calls=[];async function request(method,route,body){calls.push({method,route,body});assert.ok(!(method==='POST'&&route.startsWith('/api/v1/data-tables')),'REST table writes forbidden');assert.notEqual(method,'DELETE');if(method==='GET'&&route.startsWith('/api/v1/data-tables?'))return {data:stored,nextCursor:null};if(method==='POST'&&route==='/webhook/yt-create'){const workflow=JSON.parse(fs.readFileSync('full-stack/workflows/5x0Dy4rbBRZfov7K.json'));const code=workflow.nodes.find(n=>n.name==='Normalize Input').parameters.jsCode;const input=vm.runInNewContext('(function(){'+code+'})()',{$json:{body}})[0].json;assert.equal(input.operation,'create');assert.ok(Array.isArray(input.row.columns));assert.ok(input.row.columns.every(c=>typeof c==='object'&&typeof c.name==='string'&&['string','number','boolean','date'].includes(c.type)));const table={...body.row,id:'created-'+stored.length};stored.push(table);rows.set(table.id,[]);return [table]};if(method==='GET'&&route.startsWith('/api/v1/data-tables/'))return stored.find(t=>t.id===route.split('/').pop());if(route==='/webhook/yt-get')return [{data:rows.get(body.id),nextCursor:null}];if(route==='/webhook/yt-wright'){rows.get(body.id).push(...body.row.data);return [{success:true,insertedRows:body.row.data.length}]};throw Error('Unexpected route '+route)}return {request,stored,rows,calls}}
test('setup creates every required schema through actual CRUD normalizer, typed columns, GET readback and webhook templates only',async()=>{const f=fixture();const result=await buildRequiredTables({...f,tables,templates,includeTemplates:true,projectId:'operator-project'});assert.equal(result.ok,true);assert.equal(Object.keys(result.mapping).length,tables.length);assert.equal(f.stored.length,7);assert.equal(f.calls.filter(c=>c.route==='/webhook/yt-create').length,7);assert.equal(f.calls.filter(c=>c.route==='/webhook/yt-wright').length,1);assert.ok(f.calls.filter(c=>c.route==='/webhook/yt-create').every(c=>c.body.row.projectId==='operator-project'));assert.equal(result.schedulesActivated,false);assert.equal(result.workflowRemappingRequired,true);for(const t of f.stored)if(t.name!=='ComfyUI_Templates')assert.deepEqual(f.rows.get(t.id),[]);});
test('compatible existing schema is idempotent and template configuration never duplicated',async()=>{const f=fixture();await buildRequiredTables({...f,tables,templates,includeTemplates:true});const before=f.calls.length;await buildRequiredTables({...f,tables,templates,includeTemplates:true});assert.equal(f.stored.length,7);assert.equal(f.calls.slice(before).filter(c=>c.method==='POST'&&['/webhook/yt-create','/webhook/yt-wright'].includes(c.route)).length,0);});
test('schema conflict fails without delete or destructive migration',async()=>{const f=fixture();f.stored.push({name:tables[0].name,id:'existing',columns:[]});f.rows.set('existing',[]);await assert.rejects(buildRequiredTables({...f,tables,templates}),/Schema conflict/);assert.equal(f.stored.length,1);});
test('duplicate names and uncertain create responses fail closed',async()=>{const f=fixture();f.stored.push({name:tables[0].name,id:'a'},{name:tables[0].name,id:'b'});await assert.rejects(buildRequiredTables({...f,tables,templates}),/Ambiguous/);await assert.rejects(buildRequiredTables({request:async(m,r)=>r.includes('?')?{data:[],nextCursor:null}:[{success:true}],tables,templates}),/no table ID/);});
test('Setup route rejects foreign origin and unconfirmed input without network writes',async()=>{const f=fixture();const dir=fs.mkdtempSync(path.join(process.env.TMPDIR||os.tmpdir(),'setup-'));const handler=createSetupHandler({dataDir:dir,n8nHost:'unused',n8nPort:5678,key:'test-only',request:f.request});try{for(const [origin,body,status] of [['http://evil.example',{confirm:true},403],['http://localhost:3458',{},400],['http://localhost:3458',{confirm:true,table:'forged'},400]]){const response={writeHead(s){this.status=s},end(b){this.body=JSON.parse(b)}};await handler({method:'POST',headers:{origin,host:'localhost:3458'}},response,'/setup/build-required-tables',Buffer.from(JSON.stringify(body)));assert.equal(response.status,status)}assert.equal(f.calls.length,0);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('Setup UI build action saves every UI table mapping only after confirmed schema response, with no dispatch',async()=>{
 const html=fs.readFileSync('index.html','utf8');const start=html.indexOf('const SETUP_STEPS = [');const end=html.indexOf('// Walk the user through SETUP_STEPS',start);
 const config={tableHome:'',tableJobs:'',tableTemplates:''},calls=[],names=Object.fromEntries(tables.map((t,i)=>[t.name,'assigned-'+i]));let saved;
 const context={config,fetch:async(route,options)=>{calls.push({route,options});return {ok:true,json:async()=>({ok:true,tablesByName:names,results:[]})}},localStorage:{setItem:(k,v)=>{saved=JSON.parse(v)}},CONFIG_KEY:'test',applyLiveConfig:()=>{},readOnlyValues:()=>({}),$:()=>({value:''})};
 vm.createContext(context);vm.runInContext(html.slice(start,end)+';this.steps=SETUP_STEPS;',context);
 assert.equal(context.steps[0].key,'workflow');assert.equal(context.steps[1].key,'connect');assert.equal(context.steps[2].key,'required-tables');
 const result=await context.steps[2].action.run();assert.equal(result.ok,true);assert.equal(saved.tableMetrics,names.AI_Run_Metrics);assert.equal(saved.tableReview,names.Pipeline_Review_Gate);assert.equal(saved.tableHome,names.ComfyUI);assert.deepEqual(calls.map(c=>c.route),['/setup/build-required-tables']);
});

test('complete UI compiles and setup order is CRUD first, connectivity then explicit build without New table tab',()=>{const html=fs.readFileSync('index.html','utf8');new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1]);assert.ok(html.includes('SETUP_STEPS.unshift(crudSetupStep)'));assert.ok(html.includes("key: 'required-tables'"));assert.ok(html.includes("fetch('/setup/build-required-tables'"));assert.ok(html.includes('workflow references still require importer remapping')||html.includes('Workflow references still require importer remapping'));});
